import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle2, Search } from "lucide-react";
import { SectionTitle } from "@/components/riqsiy/SectionTitle";
import { Button } from "@/components/ui/button";
import { useProgreso } from "@/lib/progress";
import { REGISTROS_CAMPO } from "@/lib/riqsiy-regional";
export const Route=createFileRoute('/detective')({head:()=>({meta:[{title:'Detective del Patrimonio — RIQSIY'},{name:'description',content:'Resuelve un misterio patrimonial mediante fotografías, pistas, hipótesis y evidencias.'},{property:'og:title',content:'Detective del Patrimonio — RIQSIY'},{property:'og:description',content:'Observa, compara pistas y justifica una hipótesis sin inventar conclusiones.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Detective});
const PISTAS=['En la fotografía se distinguen piedras superpuestas.','La vegetación cubre parte de la estructura.','El registro no incluye una excavación ni una datación.','Una forma visible no demuestra por sí sola su función original.'];
function Detective(){const{casosResueltos,registrarHito}=useProgreso();const[pistas,setPistas]=useState(1);const[hip,setHip]=useState('');const[evid,setEvid]=useState<string[]>([]);const[fin,setFin]=useState(false);const correcto=hip==='investigar'&&evid.includes('registro')&&evid.includes('limites');const opcionesHip=[{v:'funcion',l:'Ya conocemos su función'},{v:'investigar',l:'Su función todavía requiere investigación'},{v:'natural',l:'Es una formación natural'}];const opcionesEvid=[{v:'registro',l:'El registro muestra piedras dispuestas en el terreno'},{v:'limites',l:'No hay datación, excavación ni estudio funcional'},{v:'relato',l:'Un relato basta para comprobarlo'}];return <div className="mx-auto max-w-5xl px-4 py-14"><SectionTitle eyebrow="Minijuego de razonamiento" title="Detective del Patrimonio" description="Caso 01: ¿podemos afirmar la función de esta estructura solo con la fotografía? Reúne cuatro pistas, formula una hipótesis y justifícala."/><img src={REGISTROS_CAMPO[0].src} alt="Estructura de piedra del registro propio" className="mt-8 aspect-[16/8] w-full rounded-lg object-cover"/><div className="mt-6 grid gap-3 sm:grid-cols-4">{PISTAS.map((p,i)=><button key={p} onClick={()=>setPistas(Math.max(pistas,i+1))} className={`rounded-lg border p-4 text-left text-sm ${i<pistas?'border-accent bg-accent/10':'border-dashed border-border text-muted-foreground'}`}><strong>PISTA {i+1}</strong><span className="mt-2 block">{i<pistas?p:'Bloqueada'}</span></button>)}</div>{pistas<4&&<Button className="mt-4" onClick={()=>setPistas(p=>Math.min(4,p+1))}><Search/>Revelar siguiente pista</Button>}{pistas===4&&<section className="mt-8 rounded-lg border border-border bg-card p-6"><h2 className="font-display text-xl">Formula tu hipótesis</h2>{opcionesHip.map(({v,l})=><label key={v} className="mt-3 flex gap-2 text-sm"><input type="radio" name="h" value={v} onChange={()=>setHip(v)}/>{l}</label>)}<h3 className="mt-6 font-semibold">¿Por qué elegiste esta respuesta?</h3>{opcionesEvid.map(({v,l})=><label key={v} className="mt-3 flex gap-2 text-sm"><input type="checkbox" onChange={e=>setEvid(x=>e.target.checked?[...x,v]:x.filter(i=>i!==v))}/>{l}</label>)}<Button className="mt-6" disabled={!hip||evid.length===0} onClick={()=>{setFin(true);if(correcto)registrarHito('caso','caso-estructura-01',120)}}>Resolver el caso</Button>{fin&&<div className={`mt-5 rounded-lg border p-4 text-sm ${correcto?'border-jade bg-jade/10':'border-accent bg-accent/10'}`}><p className="font-semibold">{correcto?'Caso resuelto con evidencia':'Revisa la diferencia entre observar e interpretar'}</p><p className="mt-1">La conclusión responsable es mantener la función como pregunta abierta hasta contar con investigación especializada.</p>{correcto&&<p className="mt-2"><CheckCircle2 className="mr-1 inline h-4 w-4"/>+120 RIQSI-COINS · insignia Detective del Patrimonio</p>}</div>}</section>}<p className="mt-5 text-xs text-muted-foreground">Casos resueltos: {casosResueltos.length}</p></div>}