/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PorQueRouteImport } from './routes/por-que'
import { Route as DescubreIndexRouteImport } from './routes/descubre.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueRoute = PorQueRouteImport.update({
  id: '/por-que',
  path: '/por-que',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreIndexRoute = DescubreIndexRouteImport.update({
  id: '/descubre/',
  path: '/descubre/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/por-que': typeof PorQueRoute
  '/descubre/': typeof DescubreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/por-que': typeof PorQueRoute
  '/descubre': typeof DescubreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/por-que': typeof PorQueRoute
  '/descubre/': typeof DescubreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/por-que' | '/descubre/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/por-que' | '/descubre'
  id: '__root__' | '/' | '/por-que' | '/descubre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PorQueRoute: typeof PorQueRoute
  DescubreIndexRoute: typeof DescubreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que': {
      id: '/por-que'
      path: '/por-que'
      fullPath: '/por-que'
      preLoaderRoute: typeof PorQueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre/': {
      id: '/descubre/'
      path: '/descubre'
      fullPath: '/descubre/'
      preLoaderRoute: typeof DescubreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PorQueRoute: PorQueRoute,
  DescubreIndexRoute: DescubreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
