/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntesYDespuesRouteImport } from './routes/antes-y-despues'
import { Route as CompromisoRouteImport } from './routes/compromiso'
import { Route as EscaneaRouteImport } from './routes/escanea'
import { Route as FencytRouteImport } from './routes/fencyt'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as InvestigacionRouteImport } from './routes/investigacion'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MiraMasAllaRouteImport } from './routes/mira-mas-alla'
import { Route as PorQueRouteImport } from './routes/por-que'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as TestRouteImport } from './routes/test'
import { Route as DescubreIndexRouteImport } from './routes/descubre.index'
import { Route as DescubreSlugRouteImport } from './routes/descubre.$slug'
import { Route as JuegosIndexRouteImport } from './routes/juegos.index'
import { Route as JuegosIdRouteImport } from './routes/juegos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesYDespuesRoute = AntesYDespuesRouteImport.update({
  id: '/antes-y-despues',
  path: '/antes-y-despues',
  getParentRoute: () => rootRouteImport,
} as any)
const CompromisoRoute = CompromisoRouteImport.update({
  id: '/compromiso',
  path: '/compromiso',
  getParentRoute: () => rootRouteImport,
} as any)
const EscaneaRoute = EscaneaRouteImport.update({
  id: '/escanea',
  path: '/escanea',
  getParentRoute: () => rootRouteImport,
} as any)
const FencytRoute = FencytRouteImport.update({
  id: '/fencyt',
  path: '/fencyt',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionRoute = InvestigacionRouteImport.update({
  id: '/investigacion',
  path: '/investigacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MiraMasAllaRoute = MiraMasAllaRouteImport.update({
  id: '/mira-mas-alla',
  path: '/mira-mas-alla',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueRoute = PorQueRouteImport.update({
  id: '/por-que',
  path: '/por-que',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreIndexRoute = DescubreIndexRouteImport.update({
  id: '/descubre/',
  path: '/descubre/',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreSlugRoute = DescubreSlugRouteImport.update({
  id: '/descubre/$slug',
  path: '/descubre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIndexRoute = JuegosIndexRouteImport.update({
  id: '/juegos/',
  path: '/juegos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIdRoute = JuegosIdRouteImport.update({
  id: '/juegos/$id',
  path: '/juegos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/compromiso': typeof CompromisoRoute
  '/escanea': typeof EscaneaRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre/': typeof DescubreIndexRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/compromiso': typeof CompromisoRoute
  '/escanea': typeof EscaneaRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre': typeof DescubreIndexRoute
  '/juegos': typeof JuegosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/compromiso': typeof CompromisoRoute
  '/escanea': typeof EscaneaRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre/': typeof DescubreIndexRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antes-y-despues'
    | '/compromiso'
    | '/escanea'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/mapa'
    | '/mira-mas-alla'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre/'
    | '/juegos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antes-y-despues'
    | '/compromiso'
    | '/escanea'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/mapa'
    | '/mira-mas-alla'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre'
    | '/juegos'
  id:
    | '__root__'
    | '/'
    | '/antes-y-despues'
    | '/compromiso'
    | '/escanea'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/mapa'
    | '/mira-mas-alla'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre/'
    | '/juegos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntesYDespuesRoute: typeof AntesYDespuesRoute
  CompromisoRoute: typeof CompromisoRoute
  EscaneaRoute: typeof EscaneaRoute
  FencytRoute: typeof FencytRoute
  HistoriasRoute: typeof HistoriasRoute
  InvestigacionRoute: typeof InvestigacionRoute
  MapaRoute: typeof MapaRoute
  MiraMasAllaRoute: typeof MiraMasAllaRoute
  PorQueRoute: typeof PorQueRoute
  ProgresoRoute: typeof ProgresoRoute
  RecompensasRoute: typeof RecompensasRoute
  TestRoute: typeof TestRoute
  DescubreSlugRoute: typeof DescubreSlugRoute
  JuegosIdRoute: typeof JuegosIdRoute
  DescubreIndexRoute: typeof DescubreIndexRoute
  JuegosIndexRoute: typeof JuegosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-y-despues': {
      id: '/antes-y-despues'
      path: '/antes-y-despues'
      fullPath: '/antes-y-despues'
      preLoaderRoute: typeof AntesYDespuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compromiso': {
      id: '/compromiso'
      path: '/compromiso'
      fullPath: '/compromiso'
      preLoaderRoute: typeof CompromisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanea': {
      id: '/escanea'
      path: '/escanea'
      fullPath: '/escanea'
      preLoaderRoute: typeof EscaneaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fencyt': {
      id: '/fencyt'
      path: '/fencyt'
      fullPath: '/fencyt'
      preLoaderRoute: typeof FencytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion': {
      id: '/investigacion'
      path: '/investigacion'
      fullPath: '/investigacion'
      preLoaderRoute: typeof InvestigacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mira-mas-alla': {
      id: '/mira-mas-alla'
      path: '/mira-mas-alla'
      fullPath: '/mira-mas-alla'
      preLoaderRoute: typeof MiraMasAllaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que': {
      id: '/por-que'
      path: '/por-que'
      fullPath: '/por-que'
      preLoaderRoute: typeof PorQueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre/': {
      id: '/descubre/'
      path: '/descubre'
      fullPath: '/descubre/'
      preLoaderRoute: typeof DescubreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre/$slug': {
      id: '/descubre/$slug'
      path: '/descubre/$slug'
      fullPath: '/descubre/$slug'
      preLoaderRoute: typeof DescubreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/': {
      id: '/juegos/'
      path: '/juegos'
      fullPath: '/juegos/'
      preLoaderRoute: typeof JuegosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$id': {
      id: '/juegos/$id'
      path: '/juegos/$id'
      fullPath: '/juegos/$id'
      preLoaderRoute: typeof JuegosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntesYDespuesRoute: AntesYDespuesRoute,
  CompromisoRoute: CompromisoRoute,
  EscaneaRoute: EscaneaRoute,
  FencytRoute: FencytRoute,
  HistoriasRoute: HistoriasRoute,
  InvestigacionRoute: InvestigacionRoute,
  MapaRoute: MapaRoute,
  MiraMasAllaRoute: MiraMasAllaRoute,
  PorQueRoute: PorQueRoute,
  ProgresoRoute: ProgresoRoute,
  RecompensasRoute: RecompensasRoute,
  TestRoute: TestRoute,
  DescubreSlugRoute: DescubreSlugRoute,
  JuegosIdRoute: JuegosIdRoute,
  DescubreIndexRoute: DescubreIndexRoute,
  JuegosIndexRoute: JuegosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
