/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntesYDespuesRouteImport } from './routes/antes-y-despues'
import { Route as AventuraRouteImport } from './routes/aventura'
import { Route as CompromisoRouteImport } from './routes/compromiso'
import { Route as ConstruyeAndesRouteImport } from './routes/construye-andes'
import { Route as DescubreCercaRouteImport } from './routes/descubre-cerca'
import { Route as DetectiveRouteImport } from './routes/detective'
import { Route as EscaneaRouteImport } from './routes/escanea'
import { Route as EvidenciaCampoRouteImport } from './routes/evidencia-campo'
import { Route as FencytRouteImport } from './routes/fencyt'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as InvestigacionRouteImport } from './routes/investigacion'
import { Route as LaboratorioAguaRouteImport } from './routes/laboratorio-agua'
import { Route as MachuMuquRouteImport } from './routes/machu-muqu'
import { Route as MachuMuqu3dRouteImport } from './routes/machu-muqu-3d'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MiraMasAllaRouteImport } from './routes/mira-mas-alla'
import { Route as ModoJuradoRouteImport } from './routes/modo-jurado'
import { Route as PanelInvestigadorRouteImport } from './routes/panel-investigador'
import { Route as PasaporteRouteImport } from './routes/pasaporte'
import { Route as PatrimonioLocalRouteImport } from './routes/patrimonio-local'
import { Route as PorQueRouteImport } from './routes/por-que'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as TestRouteImport } from './routes/test'
import { Route as YachaqRouteImport } from './routes/yachaq'
import { Route as YachayRouteImport } from './routes/yachay'
import { Route as DescubreIndexRouteImport } from './routes/descubre.index'
import { Route as DescubreSlugRouteImport } from './routes/descubre.$slug'
import { Route as JuegosIndexRouteImport } from './routes/juegos.index'
import { Route as JuegosIdRouteImport } from './routes/juegos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesYDespuesRoute = AntesYDespuesRouteImport.update({
  id: '/antes-y-despues',
  path: '/antes-y-despues',
  getParentRoute: () => rootRouteImport,
} as any)
const AventuraRoute = AventuraRouteImport.update({
  id: '/aventura',
  path: '/aventura',
  getParentRoute: () => rootRouteImport,
} as any)
const CompromisoRoute = CompromisoRouteImport.update({
  id: '/compromiso',
  path: '/compromiso',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstruyeAndesRoute = ConstruyeAndesRouteImport.update({
  id: '/construye-andes',
  path: '/construye-andes',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreCercaRoute = DescubreCercaRouteImport.update({
  id: '/descubre-cerca',
  path: '/descubre-cerca',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectiveRoute = DetectiveRouteImport.update({
  id: '/detective',
  path: '/detective',
  getParentRoute: () => rootRouteImport,
} as any)
const EscaneaRoute = EscaneaRouteImport.update({
  id: '/escanea',
  path: '/escanea',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenciaCampoRoute = EvidenciaCampoRouteImport.update({
  id: '/evidencia-campo',
  path: '/evidencia-campo',
  getParentRoute: () => rootRouteImport,
} as any)
const FencytRoute = FencytRouteImport.update({
  id: '/fencyt',
  path: '/fencyt',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionRoute = InvestigacionRouteImport.update({
  id: '/investigacion',
  path: '/investigacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioAguaRoute = LaboratorioAguaRouteImport.update({
  id: '/laboratorio-agua',
  path: '/laboratorio-agua',
  getParentRoute: () => rootRouteImport,
} as any)
const MachuMuquRoute = MachuMuquRouteImport.update({
  id: '/machu-muqu',
  path: '/machu-muqu',
  getParentRoute: () => rootRouteImport,
} as any)
const MachuMuqu3dRoute = MachuMuqu3dRouteImport.update({
  id: '/machu-muqu-3d',
  path: '/machu-muqu-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MiraMasAllaRoute = MiraMasAllaRouteImport.update({
  id: '/mira-mas-alla',
  path: '/mira-mas-alla',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoJuradoRoute = ModoJuradoRouteImport.update({
  id: '/modo-jurado',
  path: '/modo-jurado',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelInvestigadorRoute = PanelInvestigadorRouteImport.update({
  id: '/panel-investigador',
  path: '/panel-investigador',
  getParentRoute: () => rootRouteImport,
} as any)
const PasaporteRoute = PasaporteRouteImport.update({
  id: '/pasaporte',
  path: '/pasaporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioLocalRoute = PatrimonioLocalRouteImport.update({
  id: '/patrimonio-local',
  path: '/patrimonio-local',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueRoute = PorQueRouteImport.update({
  id: '/por-que',
  path: '/por-que',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const YachaqRoute = YachaqRouteImport.update({
  id: '/yachaq',
  path: '/yachaq',
  getParentRoute: () => rootRouteImport,
} as any)
const YachayRoute = YachayRouteImport.update({
  id: '/yachay',
  path: '/yachay',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreIndexRoute = DescubreIndexRouteImport.update({
  id: '/descubre/',
  path: '/descubre/',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubreSlugRoute = DescubreSlugRouteImport.update({
  id: '/descubre/$slug',
  path: '/descubre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIndexRoute = JuegosIndexRouteImport.update({
  id: '/juegos/',
  path: '/juegos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIdRoute = JuegosIdRouteImport.update({
  id: '/juegos/$id',
  path: '/juegos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/aventura': typeof AventuraRoute
  '/compromiso': typeof CompromisoRoute
  '/construye-andes': typeof ConstruyeAndesRoute
  '/descubre-cerca': typeof DescubreCercaRoute
  '/detective': typeof DetectiveRoute
  '/escanea': typeof EscaneaRoute
  '/evidencia-campo': typeof EvidenciaCampoRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/laboratorio-agua': typeof LaboratorioAguaRoute
  '/machu-muqu': typeof MachuMuquRoute
  '/machu-muqu-3d': typeof MachuMuqu3dRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/modo-jurado': typeof ModoJuradoRoute
  '/panel-investigador': typeof PanelInvestigadorRoute
  '/pasaporte': typeof PasaporteRoute
  '/patrimonio-local': typeof PatrimonioLocalRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/yachaq': typeof YachaqRoute
  '/yachay': typeof YachayRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre/': typeof DescubreIndexRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/aventura': typeof AventuraRoute
  '/compromiso': typeof CompromisoRoute
  '/construye-andes': typeof ConstruyeAndesRoute
  '/descubre-cerca': typeof DescubreCercaRoute
  '/detective': typeof DetectiveRoute
  '/escanea': typeof EscaneaRoute
  '/evidencia-campo': typeof EvidenciaCampoRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/laboratorio-agua': typeof LaboratorioAguaRoute
  '/machu-muqu': typeof MachuMuquRoute
  '/machu-muqu-3d': typeof MachuMuqu3dRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/modo-jurado': typeof ModoJuradoRoute
  '/panel-investigador': typeof PanelInvestigadorRoute
  '/pasaporte': typeof PasaporteRoute
  '/patrimonio-local': typeof PatrimonioLocalRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/yachaq': typeof YachaqRoute
  '/yachay': typeof YachayRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre': typeof DescubreIndexRoute
  '/juegos': typeof JuegosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antes-y-despues': typeof AntesYDespuesRoute
  '/aventura': typeof AventuraRoute
  '/compromiso': typeof CompromisoRoute
  '/construye-andes': typeof ConstruyeAndesRoute
  '/descubre-cerca': typeof DescubreCercaRoute
  '/detective': typeof DetectiveRoute
  '/escanea': typeof EscaneaRoute
  '/evidencia-campo': typeof EvidenciaCampoRoute
  '/fencyt': typeof FencytRoute
  '/historias': typeof HistoriasRoute
  '/investigacion': typeof InvestigacionRoute
  '/laboratorio-agua': typeof LaboratorioAguaRoute
  '/machu-muqu': typeof MachuMuquRoute
  '/machu-muqu-3d': typeof MachuMuqu3dRoute
  '/mapa': typeof MapaRoute
  '/mira-mas-alla': typeof MiraMasAllaRoute
  '/modo-jurado': typeof ModoJuradoRoute
  '/panel-investigador': typeof PanelInvestigadorRoute
  '/pasaporte': typeof PasaporteRoute
  '/patrimonio-local': typeof PatrimonioLocalRoute
  '/por-que': typeof PorQueRoute
  '/progreso': typeof ProgresoRoute
  '/recompensas': typeof RecompensasRoute
  '/test': typeof TestRoute
  '/yachaq': typeof YachaqRoute
  '/yachay': typeof YachayRoute
  '/descubre/$slug': typeof DescubreSlugRoute
  '/juegos/$id': typeof JuegosIdRoute
  '/descubre/': typeof DescubreIndexRoute
  '/juegos/': typeof JuegosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antes-y-despues'
    | '/aventura'
    | '/compromiso'
    | '/construye-andes'
    | '/descubre-cerca'
    | '/detective'
    | '/escanea'
    | '/evidencia-campo'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/laboratorio-agua'
    | '/machu-muqu'
    | '/machu-muqu-3d'
    | '/mapa'
    | '/mira-mas-alla'
    | '/modo-jurado'
    | '/panel-investigador'
    | '/pasaporte'
    | '/patrimonio-local'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/yachaq'
    | '/yachay'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre/'
    | '/juegos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antes-y-despues'
    | '/aventura'
    | '/compromiso'
    | '/construye-andes'
    | '/descubre-cerca'
    | '/detective'
    | '/escanea'
    | '/evidencia-campo'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/laboratorio-agua'
    | '/machu-muqu'
    | '/machu-muqu-3d'
    | '/mapa'
    | '/mira-mas-alla'
    | '/modo-jurado'
    | '/panel-investigador'
    | '/pasaporte'
    | '/patrimonio-local'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/yachaq'
    | '/yachay'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre'
    | '/juegos'
  id:
    | '__root__'
    | '/'
    | '/antes-y-despues'
    | '/aventura'
    | '/compromiso'
    | '/construye-andes'
    | '/descubre-cerca'
    | '/detective'
    | '/escanea'
    | '/evidencia-campo'
    | '/fencyt'
    | '/historias'
    | '/investigacion'
    | '/laboratorio-agua'
    | '/machu-muqu'
    | '/machu-muqu-3d'
    | '/mapa'
    | '/mira-mas-alla'
    | '/modo-jurado'
    | '/panel-investigador'
    | '/pasaporte'
    | '/patrimonio-local'
    | '/por-que'
    | '/progreso'
    | '/recompensas'
    | '/test'
    | '/yachaq'
    | '/yachay'
    | '/descubre/$slug'
    | '/juegos/$id'
    | '/descubre/'
    | '/juegos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntesYDespuesRoute: typeof AntesYDespuesRoute
  AventuraRoute: typeof AventuraRoute
  CompromisoRoute: typeof CompromisoRoute
  ConstruyeAndesRoute: typeof ConstruyeAndesRoute
  DescubreCercaRoute: typeof DescubreCercaRoute
  DetectiveRoute: typeof DetectiveRoute
  EscaneaRoute: typeof EscaneaRoute
  EvidenciaCampoRoute: typeof EvidenciaCampoRoute
  FencytRoute: typeof FencytRoute
  HistoriasRoute: typeof HistoriasRoute
  InvestigacionRoute: typeof InvestigacionRoute
  LaboratorioAguaRoute: typeof LaboratorioAguaRoute
  MachuMuquRoute: typeof MachuMuquRoute
  MachuMuqu3dRoute: typeof MachuMuqu3dRoute
  MapaRoute: typeof MapaRoute
  MiraMasAllaRoute: typeof MiraMasAllaRoute
  ModoJuradoRoute: typeof ModoJuradoRoute
  PanelInvestigadorRoute: typeof PanelInvestigadorRoute
  PasaporteRoute: typeof PasaporteRoute
  PatrimonioLocalRoute: typeof PatrimonioLocalRoute
  PorQueRoute: typeof PorQueRoute
  ProgresoRoute: typeof ProgresoRoute
  RecompensasRoute: typeof RecompensasRoute
  TestRoute: typeof TestRoute
  YachaqRoute: typeof YachaqRoute
  YachayRoute: typeof YachayRoute
  DescubreSlugRoute: typeof DescubreSlugRoute
  JuegosIdRoute: typeof JuegosIdRoute
  DescubreIndexRoute: typeof DescubreIndexRoute
  JuegosIndexRoute: typeof JuegosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-y-despues': {
      id: '/antes-y-despues'
      path: '/antes-y-despues'
      fullPath: '/antes-y-despues'
      preLoaderRoute: typeof AntesYDespuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventura': {
      id: '/aventura'
      path: '/aventura'
      fullPath: '/aventura'
      preLoaderRoute: typeof AventuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compromiso': {
      id: '/compromiso'
      path: '/compromiso'
      fullPath: '/compromiso'
      preLoaderRoute: typeof CompromisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construye-andes': {
      id: '/construye-andes'
      path: '/construye-andes'
      fullPath: '/construye-andes'
      preLoaderRoute: typeof ConstruyeAndesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre-cerca': {
      id: '/descubre-cerca'
      path: '/descubre-cerca'
      fullPath: '/descubre-cerca'
      preLoaderRoute: typeof DescubreCercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detective': {
      id: '/detective'
      path: '/detective'
      fullPath: '/detective'
      preLoaderRoute: typeof DetectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanea': {
      id: '/escanea'
      path: '/escanea'
      fullPath: '/escanea'
      preLoaderRoute: typeof EscaneaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidencia-campo': {
      id: '/evidencia-campo'
      path: '/evidencia-campo'
      fullPath: '/evidencia-campo'
      preLoaderRoute: typeof EvidenciaCampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fencyt': {
      id: '/fencyt'
      path: '/fencyt'
      fullPath: '/fencyt'
      preLoaderRoute: typeof FencytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion': {
      id: '/investigacion'
      path: '/investigacion'
      fullPath: '/investigacion'
      preLoaderRoute: typeof InvestigacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio-agua': {
      id: '/laboratorio-agua'
      path: '/laboratorio-agua'
      fullPath: '/laboratorio-agua'
      preLoaderRoute: typeof LaboratorioAguaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machu-muqu': {
      id: '/machu-muqu'
      path: '/machu-muqu'
      fullPath: '/machu-muqu'
      preLoaderRoute: typeof MachuMuquRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machu-muqu-3d': {
      id: '/machu-muqu-3d'
      path: '/machu-muqu-3d'
      fullPath: '/machu-muqu-3d'
      preLoaderRoute: typeof MachuMuqu3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mira-mas-alla': {
      id: '/mira-mas-alla'
      path: '/mira-mas-alla'
      fullPath: '/mira-mas-alla'
      preLoaderRoute: typeof MiraMasAllaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-jurado': {
      id: '/modo-jurado'
      path: '/modo-jurado'
      fullPath: '/modo-jurado'
      preLoaderRoute: typeof ModoJuradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-investigador': {
      id: '/panel-investigador'
      path: '/panel-investigador'
      fullPath: '/panel-investigador'
      preLoaderRoute: typeof PanelInvestigadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasaporte': {
      id: '/pasaporte'
      path: '/pasaporte'
      fullPath: '/pasaporte'
      preLoaderRoute: typeof PasaporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio-local': {
      id: '/patrimonio-local'
      path: '/patrimonio-local'
      fullPath: '/patrimonio-local'
      preLoaderRoute: typeof PatrimonioLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que': {
      id: '/por-que'
      path: '/por-que'
      fullPath: '/por-que'
      preLoaderRoute: typeof PorQueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yachaq': {
      id: '/yachaq'
      path: '/yachaq'
      fullPath: '/yachaq'
      preLoaderRoute: typeof YachaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yachay': {
      id: '/yachay'
      path: '/yachay'
      fullPath: '/yachay'
      preLoaderRoute: typeof YachayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre/': {
      id: '/descubre/'
      path: '/descubre'
      fullPath: '/descubre/'
      preLoaderRoute: typeof DescubreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubre/$slug': {
      id: '/descubre/$slug'
      path: '/descubre/$slug'
      fullPath: '/descubre/$slug'
      preLoaderRoute: typeof DescubreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/': {
      id: '/juegos/'
      path: '/juegos'
      fullPath: '/juegos/'
      preLoaderRoute: typeof JuegosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$id': {
      id: '/juegos/$id'
      path: '/juegos/$id'
      fullPath: '/juegos/$id'
      preLoaderRoute: typeof JuegosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntesYDespuesRoute: AntesYDespuesRoute,
  AventuraRoute: AventuraRoute,
  CompromisoRoute: CompromisoRoute,
  ConstruyeAndesRoute: ConstruyeAndesRoute,
  DescubreCercaRoute: DescubreCercaRoute,
  DetectiveRoute: DetectiveRoute,
  EscaneaRoute: EscaneaRoute,
  EvidenciaCampoRoute: EvidenciaCampoRoute,
  FencytRoute: FencytRoute,
  HistoriasRoute: HistoriasRoute,
  InvestigacionRoute: InvestigacionRoute,
  LaboratorioAguaRoute: LaboratorioAguaRoute,
  MachuMuquRoute: MachuMuquRoute,
  MachuMuqu3dRoute: MachuMuqu3dRoute,
  MapaRoute: MapaRoute,
  MiraMasAllaRoute: MiraMasAllaRoute,
  ModoJuradoRoute: ModoJuradoRoute,
  PanelInvestigadorRoute: PanelInvestigadorRoute,
  PasaporteRoute: PasaporteRoute,
  PatrimonioLocalRoute: PatrimonioLocalRoute,
  PorQueRoute: PorQueRoute,
  ProgresoRoute: ProgresoRoute,
  RecompensasRoute: RecompensasRoute,
  TestRoute: TestRoute,
  YachaqRoute: YachaqRoute,
  YachayRoute: YachayRoute,
  DescubreSlugRoute: DescubreSlugRoute,
  JuegosIdRoute: JuegosIdRoute,
  DescubreIndexRoute: DescubreIndexRoute,
  JuegosIndexRoute: JuegosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
